#!/bin/bash
# shellcheck disable=SC2034

HOME_DIR="/home/ubuntu"

# Shared comes from shell provisioner in VagrantFile
DOWNLOAD_DIR="$SHARED_DIR/downloads"

FFMPEG_VERSION=3.2.4

FITS_HOME="/opt/fits"
FITS_VERSION=1.0.7

DRUPAL_HOME="/var/www/yudl"

DJATOKA_HOME="/opt/djatoka"
